name: cursosdev_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  flutter_svg:
  cupertino_icons: ^1.0.2
  page_transition: 1.1.7+6
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/logo-cursosdev.png

  uses-material-design: true
